---
handlers:
- name: start httpd service
  service: 
    name: httpd
    state: started / stopped
  
- name: start apache2
  service: 
    name: apache2
    state: started / stopped

- name: restart httpd
  service: 
    name: httpd
    state: restarted

- name: restart apache2
  service: 
    name: apache2
    state: restarted