---
- name: setup tomcat
  hosts: all
  become: true
  tasks: 
  - name: install java
    yum:
      name: java 
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    apt:
      name: default-jdk 
      state: present
    when: ansible_os_family == "Debian"

  - name: Download tomcat packages
    get_url:
      url: wget http://mirrors.fibergrid.in/apache/tomcat/tomcat-8/v8.5.35/bin/apache-tomcat-8.5.35.tar.gz
      dest: /opt

  - name: untar tomcat package
    unarchieve: 
      src: /opt/apache-tomcat-8.5.35.tar.gz
      dest: /opt
      remote_src: yes

  - name: add execution permission on startup.sh file
    file: 
      path: /opt/apache-tomcat-8.5.35/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup startup.sh
    args: 
      chdir: /opt/apache-tomcat-8.5.35/bin
